spring:
  application:
    name: Filmes APi
  datasource:
    url: jdbc:h2:mem:filmes
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
